"use client"

import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Field, FieldGroup } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Property, PropertyPricePeriod, PropertyStatus } from "@/types";
import { Pencil } from "lucide-react";
import { useActionState, useEffect, useState } from "react";
import { updatePropertyByLandlordAction } from "../_actions/property-actions";
import { toast } from "@/components/ui/toast";
import { Separator } from "@base-ui/react";

const initialPropertyState = {
    success: false,
    message: "",
    data: {
        id: "", // will be generated by backend (uuid)
        title: "",
        description: "",
        addressLine: "",
        city: "",
        district: "",
        zipCode: null,
        latitude: null,
        longitude: null,
        price: 0, // Decimal → number
        pricePeriod: "DAILY" as PropertyPricePeriod, // default enum
        bedrooms: "",
        bathrooms: "",
        areaSqft: "",
        status: "AVAILABLE" as PropertyStatus, // default enum
        images: [],

        createdAt: new Date(), // default(now())
        updatedAt: new Date(), // @updatedAt

        landlordId: "",
        landlord: null,
        categoryId: null,
        category: null,
        rentalRequest: [],
        review: [],
    }
}

export default function EditProperty({ propertyId, property }: { propertyId: string, property: Property }) {

    const { title, price, pricePeriod, status, images, zipCode, latitude, longitude, description, city, district, addressLine } = property
    const PERIODS: PropertyPricePeriod[] = ["DAILY", "WEEKLY", "MONTHLY", "YEARLY"]
    const STATUS = [
        { label: "Available", value: "Available" },
        { label: "Unavailable", value: "UNAVAILABLE" },
        { label: "Rented", value: "RENTED" }
    ]

    const [open, setOpen] = useState(false)
    const [state, action, pending] = useActionState(updatePropertyByLandlordAction.bind(null, propertyId), initialPropertyState)

    useEffect(() => {
        if (state.success) {
            setOpen(false)
            toast.add({
                type: "success",
                title: "Property Update",
                description: "Property is updated successfully! 😎",
            })
        }

        if (!state.success) {
            toast.add({
                type: "error",
                title: "Property updation",
                description: "Property updation is failed! 👀"
            })
        }
    }, [state.success])

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger render={
                <Button variant="outline" size="icon" aria-label="Edit listing">
                    <Pencil className="h-4 w-4" />
                </Button>
            } />
            <DialogContent className="sm:max-w-sm max-h-[90vh] overflow-y-scroll">
                <form action={action}>
                    <DialogHeader>
                        <DialogTitle>Edit property</DialogTitle>
                        <DialogDescription>
                            Make changes to your property here. Click save when you&apos;re
                            done.
                        </DialogDescription>
                    </DialogHeader>
                    <FieldGroup>
                        <Field>
                            <Label htmlFor="title">Title</Label>
                            <Input id="title" name="title" defaultValue={title || ""} />
                        </Field>
                        <div className="grid grid-cols-2 gap-4">
                            <Field>
                                <Label htmlFor="price">Price</Label>
                                <Input id="price" name="price" defaultValue={price} />
                            </Field>
                            <Field>
                                <Label htmlFor="status">Status</Label>
                                <Select items={STATUS} id="status" name="status" defaultValue={status}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Property Status" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectGroup>
                                            {STATUS.map((item) => (
                                                <SelectItem key={item.value} value={item.value}>
                                                    {item.label}
                                                </SelectItem>
                                            ))}
                                        </SelectGroup>
                                    </SelectContent>
                                </Select>
                            </Field>
                        </div>
                        <Field>
                            <Label htmlFor="pricePeriod">Price Period</Label>
                            <RadioGroup name="pricePeriod" defaultValue={pricePeriod} className="w-fit grid grid-cols-2">
                                {
                                    PERIODS.map(period => (
                                        <div key={period} className="flex items-center gap-1">
                                            <RadioGroupItem value={period} id={period} />
                                            <Label htmlFor={period}>{period}</Label>
                                        </div>
                                    ))
                                }
                            </RadioGroup>
                        </Field>
                        <Field>
                            <Label htmlFor="addressLine">Address line</Label>
                            <Input id="addressLine" name="addressLine" defaultValue={addressLine || ""} />
                        </Field>
                        <Field>
                            <Label htmlFor="images">Images [links separated by (,)]</Label>
                            <Input id="images" name="images" defaultValue={images.length ? images.join(", ") : ""} />
                        </Field>
                        <Field>
                            <Label htmlFor="city">City</Label>
                            <Input id="city" name="city" defaultValue={city || ""} />
                        </Field>
                        <Field>
                            <Label htmlFor="district">District</Label>
                            <Input id="district" name="district" defaultValue={district || ""} />
                        </Field>
                        <Field>
                            <Label htmlFor="description">Description</Label>
                            <Textarea id="description" name="description" placeholder="Type your message here." defaultValue={description || ""} />
                        </Field>
                        <Separator />
                    </FieldGroup>
                    <DialogFooter>
                        <DialogClose render={<Button variant="outline">Cancel</Button>} />
                        <Button type="submit" disabled={pending}>Save changes</Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    )
}