"use client"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  Field,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { useActionState, useEffect } from "react"
import createPropertyAction from "../_actions/create-property-action"
import { PropertyPricePeriod, PropertyStatus } from "@/types"
import { Spinner } from "@/components/ui/spinner"
import { toast } from "@/components/ui/toast"

export const initialPropertyState = {
  success: false,
  message: "",
  data: {
    id: "", // will be generated by backend (uuid)
    title: "",
    description: "",
    addressLine: "",
    city: "",
    district: "",
    zipCode: null,
    latitude: null,
    longitude: null,
    price: 0, // Decimal → number
    pricePeriod: "DAILY" as PropertyPricePeriod, // default enum
    bedrooms: "",
    bathrooms: "",
    areaSqft: "",
    status: "AVAILABLE" as PropertyStatus, // default enum
    images: [],

    createdAt: new Date(), // default(now())
    updatedAt: new Date(), // @updatedAt

    landlordId: "",
    landlord: null,
    categoryId: null,
    category: null,
    rentalRequest: [],
    review: [],
  }
}

export function PropertyForm({
  className,
  ...props
}: React.ComponentProps<"form">) {

  const [state, action, isPending] = useActionState(createPropertyAction, initialPropertyState)
  useEffect(() => {

    state.success ? toast.add(
      { type: "success", title: "Property is created successfully!", description: state.message }
    ) : toast.add(
      { type: "error", title: "Property creation is failed!", description: state.message}
    )

  }, [isPending])

  console.log("property form", state)

  return (
    <form action={action} className={cn("flex flex-col gap-6", className)} {...props}>
      <FieldGroup>
        <div className="flex flex-col items-center gap-1 text-center">
          <h1 className="text-2xl font-bold">Create a property</h1>
          <p className="text-sm text-balance text-muted-foreground">
            Fill in the form below to create your property
          </p>
        </div>
        <Field>
          <FieldLabel htmlFor="title">Property Title</FieldLabel>
          <Input
            id="title"
            type="text"
            name="title"
            placeholder="New Villa"
            required
            className="bg-background"
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="price">Property Price [Per Day]</FieldLabel>
          <Input
            id="price"
            type="text"
            name="price"
            placeholder="Positive Number"
            required
            className="bg-background"
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="address">Address</FieldLabel>
          <Input
            id="address"
            type="text"
            name="address"
            placeholder="Shikalbaha, Karnaphuli"
            required
            className="bg-background"
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="city">City</FieldLabel>
          <Input
            id="city"
            type="text"
            name="city"
            placeholder="Halishahar"
            required
            className="bg-background"
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="district">District</FieldLabel>
          <Input
            id="district"
            type="text"
            name="district"
            placeholder="Chattogram"
            required
            className="bg-background"
          />
        </Field>
        <Field>
          <FieldLabel htmlFor="images">Images <small>[multiple images should be comma (,) separated]</small></FieldLabel>
          <Input
            id="images"
            type="text"
            name="images"
            placeholder="image links separated by comma (,)"
            className="bg-background"
          />
        </Field>
        <Field>
          <Button type="submit" disabled={isPending}>{isPending ? <Spinner /> : "Create a Property"}</Button>
        </Field>
      </FieldGroup>
    </form>
  )
}
